docker run -d \
    --name novaprism \
    -p 8080:2342 \
    -e PHOTOPRISM_UPLOAD_NSFW="true" \
    -e PHOTOPRISM_ADMIN_PASSWORD="missy" \
    -v ${GOPATH}/src/github.com/kris-nova/photoprism-client-go/sample-app/photoprism/import:/photoprism/import \
    -v ${GOPATH}/src/github.com/kris-nova/photoprism-client-go/sample-app/photoprism/originals:/photoprism/originals \
    -v ${GOPATH}/src/github.com/kris-nova/photoprism-client-go/sample-app/photoprism/storage:/photoprism/storage \
    krisnova/novaprism:latest

