apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism
  namespace: public
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        env:
        - name: PHOTOPRISM_DEBUG
          value: "false"
        - name: PHOTOPRISM_CACHE_PATH
          value: /photoprism/cache
        - name: PHOTOPRISM_IMPORT_PATH
          value: /photoprism/import
        - name: PHOTOPRISM_EXPORT_PATH
          value: /photoprism/export
        - name: PHOTOPRISM_ORIGINALS_PATH
          value: /photoprism/originals
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_DATABASE_SERVER
          value: 10.0.0.188
        - name: PHOTOPRISM_DATABASE_NAME
          value: novaphotos
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
          - mountPath: /photoprism/originals
            name: originals
          - mountPath: /photoprism/import
            name: import
          - mountPath: /photoprism/export
            name: export
          - mountPath: /photoprism/cache
            name: cache
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: http
      volumes:
      - name: originals
        hostPath:
          path: /data/photoprism/originals
      - name: import
        hostPath:
          path: /data/photoprism/import
      - name: export
        hostPath:
          path: /data/photoprism/export
      - name: cache
        hostPath:
          path: /data/photoprism/cache
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: public
spec:
  ports:
    - nodePort: 30001
      port: 2342
      protocol: TCP
      targetPort: 2342
  selector:
    app: photoprism
  type: NodePort